version: '3.9'

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 7801M
    ports:
      - 7200:3001
    restart: always
    volumes:
      - ./data:/app/data
    network_mode: bridge
    privileged: false
    environment:
      - ADMIN_PASSWORD=<password here>
      - ADMIN_EMAIL=<email here>